spring.application.name=music-platform

backblaze.credentials.access-key=${BACKBLAZE_ACCESS_KEY}
backblaze.credentials.secret-key=${BACKBLAZE_SECRET_KEY}
backblaze.region=${BACKBLAZE_REGION}
backblaze.s3.endpoint=${BACKBLAZE_S3_ENDPOINT}
backblaze.bucket.name=${BACKBLAZE_S3_BUCKET}

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
#spring.datasource.url=jdbc:postgresql://172.19.0.2:5432/music_platform
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
server.error.include-message=always
spring.jpa.open-in-view=false
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.location=${TEMP_LOCATION}

jwt.expiration-time=${JWT_EXPIRATION_TIME}

admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}
admin.username=${ADMIN_USERNAME}
admin.role=${ADMIN_ROLE}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

ml.service.url.upload=${ML_SERVICE_URL_UPLOAD}
ml.service.url.delete=${ML_SERVICE_URL_DELETE}
ml.service.url.recommendations=${ML_SERVICE_URL_RECOMMENDATIONS}
